### ISSUE TITLE
Unterschiedliche Keybinds für PC und Arcane Automaten

### ISSUE THREAD

**Issue by TheBlackDragon4** [TheBlackDragon4/FrankenGameJam2024#10]

**Comment by NicoTheCode** [comment]
If you want to change the key bind function names in the future, you have to change it in the following locations:
- Project Settings/Input Map
- res://addons/modular-settings-menu/scenes/settings-elements/controls-elements/input_settings.tscn::GDScript_te2ja
- res://etc/keybinds_arcade.json
